### ISSUE TITLE
SOW 1 Status

### ISSUE THREAD

**Issue by robnagler** [radiasoft/zgoubi#19]
This issue is used to track the state of the SOW.

- [x] created
- [x] RadiaSoft acknowledgement
- [x] Sourcery acknowledgement
- [x] Sourcery completed
- [x] RadiaSoft accepted

**Comment by robnagler** [comment]
@rouson and @robnagler signed the acknowledgement.

**Comment by robnagler** [comment]
This is tracking the life of the SOW so it has to stay open until the SOW is completed and accepted.

**Comment by dtabell** [comment]
I reviewed all of Damian's commits (some from Zaak also).
This closes SOW1.

**Comment by robnagler** [comment]
Please see https://github.com/radiasoft/zgoubi/issues/19#issuecomment-403858742

This is not closed until we have signatures on the SOW.

**Comment by rouson** [comment]
@robnagler  Does the following status of the issues under the SOW 1 reflect the current state of acceptance of the deliverables?

* Closed issues: #1, #2, #9, #10. 
* Open issue: #4.  

Please reopen any closed issues that are not accepted and comment on what is required for acceptance.  And please let me know if there is anything left to do to close the one open issue.

In particular, let me know if you want me to delete the `install.sh` script or strip it down to a few lines as you suggested.  My preference would be to delete it rather than to strip it down.  I worry that a stripped down version would grow over time and lead to reinserting a good portion of what was taken out.  I use install scripts to capture my own workflow and offered it in case it simplifies anyone else's workflow too, but I understand the downsides, particularly in terms of the hurdle it poses to doing a complete code review and the complexity associated with supporting Apple's default bash 3. It would be great if you and @dtabell could discuss the portability question.  I am fine with proceeding however you both see fit.

**Comment by dtabell** [comment]
Since one can use homebrew to install bash 4 on mac os x,
I don't see the need support bash 3.

**Comment by rouson** [comment]
@dtabell  After a bit more reading, I think I now understand @robnagler's suggestion better.   The RadiaSoft development environment _is_ the portability solution because it can be deployed anywhere vagrant and a virtualization platform (e.g., VirtualBox) are installed.  This renders moot any OS-specific issues such as choosing between macOS's default bash 3 versus the newer bash 4.
