### ISSUE TITLE
Generate FORD documentation

### ISSUE THREAD

**Issue by rouson** [radiasoft/zgoubi#9]
The goal here is to expose whatever information about code structure -- namely dependencies and call graphs -- we can glean from running the [FORD] Fortran documentation generator on the zgoubi source.  This information could be useful in deciding on a progression of refactoring phases and in determining the feasibility of certain refactoring steps.

[FORD]: https://github.com/cmacmackin/ford/

**Comment by rouson** [comment]
The deliverable associated with this issue is now ready for review on the [develop] branch.  To review the deliverable, execute commands like the following in a `bash` shel on macOS:
```bash
git clone -b develop https://github.com/radiasoft/zgoubi
./install.sh --documentation-only 
open doc/index.html
```
or open the above file on Linux using the desired browser such as
```
firefox doc/index.html
```
Windows Subsystem for Linux ([WSL]) provides only a command line but does not support graphics so it won't be possible to view the HTML files directly in WSL, but I believe Windows can access the WSL file system, in which case any Windows browser should work as long as it is launched outside of WSL.

Although the generated HTML files should not be stored in the repository, it might be a good idea to host the HTML documentation on the [wiki] associated with this repository. 

[develop]: https://github.com/radiasoft/zgoubi/tree/develop
[WSL]: https://docs.microsoft.com/en-us/windows/wsl/install-win10
[wiki]: https://github.com/radiasoft/zgoubi/wiki

**Comment by zbeekman** [comment]
> Although the generated HTML files should not be stored in the repository, it might be a good idea to host the HTML documentation on the wiki associated with this repository.

I don't think hosting in the wiki is feasible, but if the source code is open, then the API documentation can easily be generated during CI testing (#10) and automatically pushed to the github pages (`gh-pages` branch) upon successful completion of the CI build. It would then be available at https://radiasoft.github.io/zgoubi.

**Comment by robnagler** [comment]
We should use a separate repo or something like readthedocs.io, to do the hosting. 

The problem with a gh-pages branch is the repo continues to grow every time you checkin a change. This makes the source repo too large over time, especially if we are hosting PDFs.

**Comment by zbeekman** [comment]
Yes, I understand your concerns.

A little bit of background:

FORD generates HTML based documentation, so I'm not sure wether or not it can integrate with readthedocs.io. Any cheap/free static HTML hosting solution is fine. With `gh-pages` the branch may be created as an orphan branch so it shares no history with the main repo. Also, there won't be PDF's just some .svg images and HTML/js/css files. If it is *not* minified then git should be able to track the deltas without taking up too much extra space. `git clone --single-branch --branch=<branch_name> ...` can be used to speed up cloning too.

But I definitely hear your concerns and I'm sure we can work with whatever your preferred documentation hosting solution is. Anything that can be accessed with an ssh keypair or private token can be securely used for hosting, through [encrypted variables](https://docs.travis-ci.com/user/environment-variables#Defining-encrypted-variables-in-.travis.yml) on Travis-CI.com. (i.e., only those with push access to the repository could compromise the secret token/key; 3rd party pull requests etc. have the key/token scrubbed from the CI environment so it won't "leak".)

**Comment by zbeekman** [comment]
Oh, I just re-read your comment and noticed the mention of a separate repository. That would be completely fine. You could make it have just the one gh-pages branch (and/or branches to track the corresponding branch on the main repository). If you called it zgoubi-doc or something that would work. A GH token or SSH-keypair would still be needed to push to it from the CI setup.

**Comment by robnagler** [comment]
I think we should create zgoubi.github.io as the repo, since that's canonical. I just bought zgoubi.com so we can make that the CNAME.

**Comment by zbeekman** [comment]
> I think we should create zgoubi.github.io as the repo, since that's canonical

Will that work with a *project*? My understanding was that <org/user>.github.io was supported, and any project pages would then be at <org/user>.github.io/<project>. I believe that still applies unless they have changed something recently.

**Comment by robnagler** [comment]
I was thinking we'd only use the CNAME, and not publicize the URL zgoubi.github.io.github.io. I believe in [owning our namespace](https://www.viarob.com/my/page/Digital_Name_Management).

My thinking was that by identifying the repo as radiasoft/zgoubi.github.io it would be clear what it was for as opposed to zgoubi-docs, which doesn't indicate it is a GH pages repo. People might be confused by the fact you can't publish a github.io URL not matching the org's name, but a README can explain what the repo is for and how it is generated.

We could also use zgoubi/zgoubi.github.io, since we own the org zgoubi (as I write this :). Not sure we want to go down that path just right now. There's value to us branding RadiaSoft and Zgoubi together.

**Comment by zbeekman** [comment]
> My thinking was that by identifying the repo as radiasoft/zgoubi.github.io it would be clear what it was for as opposed to zgoubi-docs, which doesn't indicate it is a GH pages repo.

OK sounds good to me!

> I was thinking we'd only use the CNAME, and not publicize the URL zgoubi.github.io.github.io

Also sounds good. However, AFAIK, if you create radiasoft/zgoubi.github.io it would not be accessible at zgoubi.github.io.github.io, but rather at radiasoft.github.io/zgoubi.github.io.

For example, [JSON-Fortran](https://github.com/jacobwilliams/json-fortran) hosts FORD documentation in their gh-pages branch and the URL is, by necessity, https://jacobwilliams.github.io/json-fortran. (I helped setup the CI deployment of the documentation. I often have a fork too, and since I host my personal website )

**Comment by robnagler** [comment]
I setup A records, which is fine. zgoubi.com is live. I need to setup travis and other things. I'll probably do that this weekend.

**Comment by zbeekman** [comment]
I've found that

1) Cloudflare is great for free DNS service w/ github pages
2) To get proper end to end strict SSL encryption CNAME records work better than A records using cloudflare (but I'm no networking expert)

If you have any trouble setting up travis-ci feel free to reach out (even on a Saturday or Sunday). My email is is ibeekman/paratools.com.

**Comment by robnagler** [comment]
Thanks. We use Cloudflare client-side. We run our own DNS server side.

letsencrypt has leveled the playing field (and also made TLS less secure :). zgoubi.com is already https-only.

They even figure out the www redirect.

I edited your comment, because you probably don't want your email address in the wild.
